import Foundation
import Compression

/// On-device barcode → product attributes lookup over the bundled USDA-Branded
/// corpus. Fully offline: no per-scan network call (the privacy line — see
/// docs/design/barcode-capture.md). Two memory-mapped files, generated by
/// `scripts/food/build_barcode_corpus.py`:
///   - `barcode-index.bin` : GTIN-sorted fixed-size records → binary search.
///   - `barcode-names.bin`  : names in 256-record chunks, each raw-DEFLATE'd →
///                            one small inflate per hit, ~0 resident memory.
///
/// Format (must stay in lockstep with the generator):
///   index : "KBIX" | u16 ver | u16 chunk | u32 count | count × record
///           record = u64 gtin (LE, ascending) | u8 flags | 5× u8 macro
///           flags bit i set ⇒ macro i known; "known" ≠ a real 0 value.
///           macro order = protein, fat, sugar, fiber, caffeine.
///   names : "KBNM" | u16 ver | u16 chunk | u32 nchunks
///           | (nchunks+1)× u32 offset | nchunks× u32 rawlen | deflate chunks.
///           record i's name = chunk i/chunk, item i%chunk; each = u16 len + utf8.
nonisolated final class BarcodeCorpus: Sendable {

    /// Loaded once from the app bundle. Falls back to an empty (unavailable) corpus
    /// if the resources aren't present, so a lookup just returns nil — never crashes.
    static let shared: BarcodeCorpus = {
        func url(_ base: String) -> URL? {
            Bundle.main.url(forResource: base, withExtension: "bin", subdirectory: "Food")
                ?? Bundle.main.url(forResource: base, withExtension: "bin")
        }
        guard let iu = url("barcode-index"), let nu = url("barcode-names"),
              let idata = try? Data(contentsOf: iu, options: .mappedIfSafe),
              let ndata = try? Data(contentsOf: nu, options: .mappedIfSafe)
        else { return BarcodeCorpus(indexData: Data(), namesData: Data()) }
        return BarcodeCorpus(indexData: idata, namesData: ndata)
    }()

    /// A resolved product. Macro values are grams per 100 g (caffeine = mg per 100 g);
    /// `nil` = the label didn't report that macro — kept distinct from a real 0
    /// (sugar-free ≠ sugar-unknown) so the reduction never reads missing as absent.
    struct Product: Sendable, Equatable {
        let gtin: UInt64
        let name: String
        let protein: Int?
        let fat: Int?
        let sugar: Int?
        let fiber: Int?
        let caffeine: Int?
    }

    private let index: Data
    private let names: Data
    private let count: Int
    private let chunk: Int
    private let nChunks: Int
    private let rawBase: Int      // start of the per-chunk raw-length table in `names`
    private let dataBase: Int     // start of the deflate chunk data in `names`
    let available: Bool

    private static let hdr = 12          // header bytes on both files
    private static let recSize = 14      // u64 + u8 + 5×u8
    private static let offBase = 12      // names: offset table starts right after header

    /// Designated init from the two raw file images (bundle- or test-supplied).
    /// Invalid/empty input yields an unavailable corpus rather than a failure.
    init(indexData: Data, namesData: Data) {
        guard indexData.count >= Self.hdr, namesData.count >= Self.hdr,
              indexData.prefix(4).elementsEqual("KBIX".utf8),
              namesData.prefix(4).elementsEqual("KBNM".utf8)
        else {
            self.index = Data(); self.names = Data()
            self.count = 0; self.chunk = 1; self.nChunks = 0
            self.rawBase = 0; self.dataBase = 0; self.available = false
            return
        }
        self.index = indexData
        self.names = namesData
        self.chunk = max(1, Int(indexData.leU16(6)))
        self.count = Int(indexData.leU32(8))
        self.nChunks = Int(namesData.leU32(8))
        self.rawBase = Self.offBase + 4 * (self.nChunks + 1)
        self.dataBase = self.rawBase + 4 * self.nChunks
        self.available = true
    }

    // MARK: - Public API

    /// Normalize a scanned barcode string to the corpus's integer key: digits only,
    /// leading zeros dropped (a US UPC-A is an EAN-13 minus its leading zero, and the
    /// corpus is keyed on the integer form). Returns nil for a code with no digits.
    static func normalize(_ scanned: String) -> UInt64? {
        let digits = scanned.unicodeScalars.filter { $0.value >= 48 && $0.value <= 57 }
        guard !digits.isEmpty else { return nil }
        return UInt64(String(String.UnicodeScalarView(digits)))
    }

    /// Look up a raw scanned barcode string. nil = not in the corpus (caller falls
    /// through to manual/voice entry — never a dead end).
    func product(forScanned code: String) -> Product? {
        guard let g = Self.normalize(code) else { return nil }
        return product(forGTIN: g)
    }

    func product(forGTIN gtin: UInt64) -> Product? {
        guard available, count > 0 else { return nil }
        var lo = 0, hi = count - 1
        while lo <= hi {
            let mid = (lo + hi) / 2
            let g = self.gtin(at: mid)
            if g == gtin { return record(mid) }
            if g < gtin { lo = mid + 1 } else { hi = mid - 1 }
        }
        return nil
    }

    /// Reduce a product's macros to the engine's coarse presence set (the same
    /// `[FoodAttribute]` the text classifier emits). Thresholds are per-100 g and
    /// PROVISIONAL — a "meaningful source of" cut, pending validation against the
    /// FoodDB attribute semantics. Unknown macros never count as present.
    func attributes(_ p: Product) -> [FoodAttribute] {
        var set = Set<FoodAttribute>()
        if let v = p.protein,  v >= 5 { set.insert(.protein) }
        if let v = p.fat,      v >= 3 { set.insert(.fat) }
        if let v = p.sugar,    v >= 5 { set.insert(.sugar) }
        if let v = p.fiber,    v >= 3 { set.insert(.fiber) }
        if let v = p.caffeine, v >  0 { set.insert(.caffeine) }
        return FoodAttribute.allCases.filter { set.contains($0) }
    }

    // MARK: - Record decode

    private func gtin(at i: Int) -> UInt64 {
        index.leU64(Self.hdr + i * Self.recSize)
    }

    private func record(_ i: Int) -> Product {
        let o = Self.hdr + i * Self.recSize
        let flags = index[index.startIndex + o + 8]
        func macro(_ bit: Int) -> Int? {
            (flags & (1 << bit)) != 0 ? Int(index[index.startIndex + o + 9 + bit]) : nil
        }
        return Product(
            gtin: index.leU64(o), name: name(at: i),
            protein: macro(0), fat: macro(1), sugar: macro(2),
            fiber: macro(3), caffeine: macro(4))
    }

    private func name(at i: Int) -> String {
        let c = i / chunk, item = i % chunk
        guard c < nChunks else { return "" }
        let start = dataBase + Int(names.leU32(Self.offBase + c * 4))
        let end = dataBase + Int(names.leU32(Self.offBase + (c + 1) * 4))
        let rawLen = Int(names.leU32(rawBase + c * 4))
        guard start < end, end <= names.count, rawLen > 0 else { return "" }
        let comp = names.subdata(in: (names.startIndex + start)..<(names.startIndex + end))
        guard let blob = Self.inflate(comp, rawSize: rawLen) else { return "" }
        var o = 0
        for _ in 0..<item {
            guard o + 2 <= blob.count else { return "" }
            o += 2 + (Int(blob[o]) | (Int(blob[o + 1]) << 8))
        }
        guard o + 2 <= blob.count else { return "" }
        let ln = Int(blob[o]) | (Int(blob[o + 1]) << 8)
        o += 2
        guard o + ln <= blob.count else { return "" }
        return String(decoding: blob[o..<(o + ln)], as: UTF8.self)
    }

    /// Raw-DEFLATE inflate via Apple's Compression framework (COMPRESSION_ZLIB is
    /// raw deflate, matching the generator's wbits=-15). `rawSize` is exact, so the
    /// destination is sized once — no growth loop.
    private static func inflate(_ src: Data, rawSize: Int) -> [UInt8]? {
        var dst = [UInt8](repeating: 0, count: rawSize)
        let written = src.withUnsafeBytes { srcRaw -> Int in
            guard let srcPtr = srcRaw.bindMemory(to: UInt8.self).baseAddress else { return 0 }
            return dst.withUnsafeMutableBytes { dstRaw in
                guard let dstPtr = dstRaw.bindMemory(to: UInt8.self).baseAddress else { return 0 }
                return compression_decode_buffer(dstPtr, rawSize, srcPtr, src.count, nil, COMPRESSION_ZLIB)
            }
        }
        return written == rawSize ? dst : nil
    }
}

// Little-endian integer reads at an absolute byte offset (relative to startIndex),
// safe for a memory-mapped Data whose startIndex may be non-zero.
private extension Data {
    func leU16(_ o: Int) -> UInt16 {
        let b = startIndex + o
        return UInt16(self[b]) | (UInt16(self[b + 1]) << 8)
    }
    func leU32(_ o: Int) -> UInt32 {
        let b = startIndex + o
        return UInt32(self[b]) | (UInt32(self[b + 1]) << 8)
            | (UInt32(self[b + 2]) << 16) | (UInt32(self[b + 3]) << 24)
    }
    func leU64(_ o: Int) -> UInt64 {
        let b = startIndex + o
        var v: UInt64 = 0
        for k in 0..<8 { v |= UInt64(self[b + k]) << (8 * k) }
        return v
    }
}
